"""extend industry reports schema

Revision ID: c7dbcc78614f
Revises: 705a5833d4a3
Create Date: 2026-07-07 17:53:38.712474

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7dbcc78614f'
down_revision: str | None = '705a5833d4a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry_reports', sa.Column('report_id', sa.Text(), nullable=False))
    op.add_column('industry_reports', sa.Column('question_type', sa.Text(), nullable=True))
    op.add_column('industry_reports', sa.Column('status', sa.Text(), nullable=False))
    op.add_column('industry_reports', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('industry_reports', sa.Column('schema_version', sa.Text(), nullable=False))
    op.add_column('industry_reports', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('industry_reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('industry_reports', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index('idx_industry_reports_created_at', 'industry_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_industry_reports_payload_gin', 'industry_reports', ['payload'], unique=False, postgresql_using='gin')
    op.create_index('idx_industry_reports_question_type', 'industry_reports', ['question_type'], unique=False)
    op.create_index('idx_industry_reports_request_id', 'industry_reports', ['request_id'], unique=False)
    op.create_index('idx_industry_reports_trace_id', 'industry_reports', ['trace_id'], unique=False)
    op.create_unique_constraint(op.f('uq_industry_reports_report_id'), 'industry_reports', ['report_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_industry_reports_report_id'), 'industry_reports', type_='unique')
    op.drop_index('idx_industry_reports_trace_id', table_name='industry_reports')
    op.drop_index('idx_industry_reports_request_id', table_name='industry_reports')
    op.drop_index('idx_industry_reports_question_type', table_name='industry_reports')
    op.drop_index('idx_industry_reports_payload_gin', table_name='industry_reports', postgresql_using='gin')
    op.drop_index('idx_industry_reports_created_at', table_name='industry_reports')
    op.alter_column('industry_reports', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('industry_reports', 'updated_at')
    op.drop_column('industry_reports', 'error_message')
    op.drop_column('industry_reports', 'schema_version')
    op.drop_column('industry_reports', 'payload')
    op.drop_column('industry_reports', 'status')
    op.drop_column('industry_reports', 'question_type')
    op.drop_column('industry_reports', 'report_id')
    # ### end Alembic commands ###
