"""add stock_corp_codes

Revision ID: 6ca978063906
Revises: 4a21292e89fc
Create Date: 2026-07-08 16:41:38.511434

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca978063906'
down_revision: str | None = '4a21292e89fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_corp_codes',
    sa.Column('stock_code', sa.String(), nullable=False),
    sa.Column('corp_code', sa.String(), nullable=False),
    sa.Column('corp_name_from_dart', sa.Text(), nullable=False),
    sa.Column('modify_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('stock_code', name=op.f('pk_stock_corp_codes')),
    sa.UniqueConstraint('corp_code', name='uq_stock_corp_codes_corp_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_corp_codes')
    # ### end Alembic commands ###
