"""add stock aliases

Revision ID: 4a21292e89fc
Revises: c7dbcc78614f
Create Date: 2026-07-07 18:31:26.960823

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a21292e89fc'
down_revision: str | None = 'c7dbcc78614f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_aliases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stock_code', sa.String(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("normalized_alias <> ''", name='ck_stock_aliases_normalized_alias_not_empty'),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], name=op.f('fk_stock_aliases_stock_code_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_aliases')),
    sa.UniqueConstraint('normalized_alias', 'stock_code', name='uq_stock_aliases_normalized_alias_stock_code')
    )
    op.create_index('idx_stock_aliases_stock_code', 'stock_aliases', ['stock_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_aliases_stock_code', table_name='stock_aliases')
    op.drop_table('stock_aliases')
    # ### end Alembic commands ###
