"""add integrated postgresql schema

Revision ID: 705a5833d4a3
Revises:
Create Date: 2026-07-07 14:25:47.771752

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector  # news.embedding VECTOR 타입 렌더에 필요
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '705a5833d4a3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 확장 먼저: pgcrypto=gen_random_uuid() 기본값, vector=news.embedding 타입.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('stock_name', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('base_date', sa.Date(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flow_reports'))
    )
    op.create_index('ix_flow_reports_ticker_base_date', 'flow_reports', ['ticker', sa.literal_column('base_date DESC')], unique=False)
    op.create_index('ix_flow_reports_trace_id', 'flow_reports', ['trace_id'], unique=False)
    op.create_table('industry_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('client_session_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry_reports'))
    )
    op.create_table('news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news')),
    sa.UniqueConstraint('url', name=op.f('uq_news_url'))
    )
    op.create_index('ix_news_event_id', 'news', ['event_id'], unique=False)
    op.create_index('ix_news_published_at', 'news', ['published_at'], unique=False)
    op.create_table('news_reports',
    sa.Column('report_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_news_reports'))
    )
    op.create_index('ix_news_reports_created_at', 'news_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('stocks',
    sa.Column('stock_code', sa.String(), nullable=False),
    sa.Column('stock_name', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('stock_code', name=op.f('pk_stocks'))
    )
    op.create_table('technical_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('client_session_id', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('stock_name', sa.String(), nullable=True),
    sa.Column('original_query', sa.Text(), nullable=True),
    sa.Column('normalized_query', sa.Text(), nullable=True),
    sa.Column('analysis_focus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_regime', sa.String(), nullable=False),
    sa.Column('daily_regime', sa.String(), nullable=False),
    sa.Column('weekly_trend', sa.String(), nullable=True),
    sa.Column('monthly_trend', sa.String(), nullable=True),
    sa.Column('alignment_flag', sa.String(), nullable=False),
    sa.Column('regime_context', sa.Text(), nullable=True),
    sa.Column('consensus', sa.String(), nullable=True),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_basis', sa.String(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_reports')),
    sa.UniqueConstraint('request_id', name=op.f('uq_technical_reports_request_id'))
    )
    op.create_index('ix_technical_reports_client_session_id_created_at', 'technical_reports', ['client_session_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_technical_reports_ticker_as_of', 'technical_reports', ['ticker', sa.literal_column('as_of DESC')], unique=False)
    op.create_index('ix_technical_reports_trace_id', 'technical_reports', ['trace_id'], unique=False)
    op.create_table('agent_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('agent_report_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('client_session_id', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_session_id', sa.UUID(), nullable=True),
    sa.Column('stock_code', sa.String(), nullable=True),
    sa.Column('stock_name', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], name=op.f('fk_agent_reports_stock_code_stocks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_reports'))
    )
    op.create_index('ix_agent_reports_agent_type_created_at', 'agent_reports', ['agent_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_agent_reports_client_session_id_created_at', 'agent_reports', ['client_session_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_agent_reports_stock_code_created_at', 'agent_reports', ['stock_code', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_agent_reports_trace_id', 'agent_reports', ['trace_id'], unique=False)
    op.create_table('flow_report_interpretations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('interpretation_source', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['flow_reports.id'], name=op.f('fk_flow_report_interpretations_report_id_flow_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flow_report_interpretations')),
    sa.UniqueConstraint('report_id', name=op.f('uq_flow_report_interpretations_report_id'))
    )
    op.create_table('flow_report_verifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('gate1_passed', sa.Boolean(), nullable=True),
    sa.Column('gate2_passed', sa.Boolean(), nullable=True),
    sa.Column('gate3_passed', sa.Boolean(), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('regen_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['flow_reports.id'], name=op.f('fk_flow_report_verifications_report_id_flow_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flow_report_verifications')),
    sa.UniqueConstraint('report_id', name=op.f('uq_flow_report_verifications_report_id'))
    )
    op.create_table('fundamental_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('stock_code', sa.String(), nullable=True),
    sa.Column('corp_code', sa.String(), nullable=True),
    sa.Column('bsns_year', sa.Integer(), nullable=True),
    sa.Column('years', sa.Integer(), nullable=True),
    sa.Column('fs_div', sa.String(), nullable=True),
    sa.Column('report_mode', sa.String(), nullable=True),
    sa.Column('reprt_code', sa.String(), nullable=True),
    sa.Column('reprt_name', sa.String(), nullable=True),
    sa.Column('period_label', sa.String(), nullable=True),
    sa.Column('verdict_label', sa.String(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('fin_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_html', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('dart_calls', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], name=op.f('fk_fundamental_reports_stock_code_stocks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental_reports'))
    )
    op.create_index('ix_fundamental_reports_request_id', 'fundamental_reports', ['request_id'], unique=False)
    op.create_index('ix_fundamental_reports_stock_code_as_of', 'fundamental_reports', ['stock_code', sa.literal_column('as_of DESC')], unique=False)
    op.create_index('ix_fundamental_reports_trace_id', 'fundamental_reports', ['trace_id'], unique=False)
    op.create_table('technical_report_charts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('candle_unit', sa.String(), nullable=True),
    sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chart_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['technical_reports.id'], name=op.f('fk_technical_report_charts_report_id_technical_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_report_charts'))
    )
    op.create_index('ix_technical_report_charts_report_id_period', 'technical_report_charts', ['report_id', 'period'], unique=False)
    op.create_table('technical_report_followups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('client_session_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['technical_reports.id'], name=op.f('fk_technical_report_followups_report_id_technical_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_report_followups'))
    )
    op.create_index('ix_technical_report_followups_report_id_created_at', 'technical_report_followups', ['report_id', 'created_at'], unique=False)
    op.create_table('technical_report_interpretations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('interpretation_source', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('template_fallback_used', sa.Boolean(), nullable=False),
    sa.Column('detail_source_count', sa.Integer(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['technical_reports.id'], name=op.f('fk_technical_report_interpretations_report_id_technical_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_report_interpretations')),
    sa.UniqueConstraint('report_id', name=op.f('uq_technical_report_interpretations_report_id'))
    )
    op.create_table('technical_report_risk_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ref_price', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['technical_reports.id'], name=op.f('fk_technical_report_risk_notes_report_id_technical_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_report_risk_notes'))
    )
    op.create_index('ix_technical_report_risk_notes_report_id_severity', 'technical_report_risk_notes', ['report_id', 'severity'], unique=False)
    op.create_table('technical_report_signals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('signal', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_unit', sa.String(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('detail_source', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['technical_reports.id'], name=op.f('fk_technical_report_signals_report_id_technical_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_report_signals')),
    sa.UniqueConstraint('report_id', 'indicator', name='uq_technical_report_signals_report_id_indicator')
    )
    op.create_table('technical_report_verifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('calc_passed', sa.Boolean(), nullable=False),
    sa.Column('regime_passed', sa.Boolean(), nullable=False),
    sa.Column('label_matched', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('regen_count', sa.Integer(), nullable=False),
    sa.Column('failed_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['technical_reports.id'], name=op.f('fk_technical_report_verifications_report_id_technical_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_report_verifications')),
    sa.UniqueConstraint('report_id', name=op.f('uq_technical_report_verifications_report_id'))
    )
    op.create_table('fundamental_report_interpretations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('interpretation_source', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['fundamental_reports.id'], name=op.f('fk_fundamental_report_interpretations_report_id_fundamental_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental_report_interpretations')),
    sa.UniqueConstraint('report_id', name=op.f('uq_fundamental_report_interpretations_report_id'))
    )
    op.create_table('fundamental_report_verifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('binding_passed', sa.Boolean(), nullable=True),
    sa.Column('consistency_passed', sa.Boolean(), nullable=True),
    sa.Column('verdict_stable', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('regen_count', sa.Integer(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('guard_violations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['fundamental_reports.id'], name=op.f('fk_fundamental_report_verifications_report_id_fundamental_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental_report_verifications')),
    sa.UniqueConstraint('report_id', name=op.f('uq_fundamental_report_verifications_report_id'))
    )
    op.create_table('report_filing_snippets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('rcept_no', sa.String(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['fundamental_reports.id'], name=op.f('fk_report_filing_snippets_report_id_fundamental_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_filing_snippets'))
    )
    op.create_table('report_insights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=True),
    sa.Column('source_endpoint', sa.String(), nullable=True),
    sa.Column('rcept_no', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['fundamental_reports.id'], name=op.f('fk_report_insights_report_id_fundamental_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_insights'))
    )
    op.create_table('report_ratios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('ratio_name', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('display_value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('formula', sa.String(), nullable=True),
    sa.Column('basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['fundamental_reports.id'], name=op.f('fk_report_ratios_report_id_fundamental_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_ratios'))
    )
    op.create_table('report_evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('ratio_id', sa.UUID(), nullable=True),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('claim', sa.String(), nullable=True),
    sa.Column('rcept_no', sa.String(), nullable=True),
    sa.Column('bsns_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(), nullable=True),
    sa.Column('sj_div', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('account_nm', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('display_value', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ratio_id'], ['report_ratios.id'], name=op.f('fk_report_evidence_ratio_id_report_ratios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['fundamental_reports.id'], name=op.f('fk_report_evidence_report_id_fundamental_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_evidence'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_evidence')
    op.drop_table('report_ratios')
    op.drop_table('report_insights')
    op.drop_table('report_filing_snippets')
    op.drop_table('fundamental_report_verifications')
    op.drop_table('fundamental_report_interpretations')
    op.drop_table('technical_report_verifications')
    op.drop_table('technical_report_signals')
    op.drop_index('ix_technical_report_risk_notes_report_id_severity', table_name='technical_report_risk_notes')
    op.drop_table('technical_report_risk_notes')
    op.drop_table('technical_report_interpretations')
    op.drop_index('ix_technical_report_followups_report_id_created_at', table_name='technical_report_followups')
    op.drop_table('technical_report_followups')
    op.drop_index('ix_technical_report_charts_report_id_period', table_name='technical_report_charts')
    op.drop_table('technical_report_charts')
    op.drop_index('ix_fundamental_reports_trace_id', table_name='fundamental_reports')
    op.drop_index('ix_fundamental_reports_stock_code_as_of', table_name='fundamental_reports')
    op.drop_index('ix_fundamental_reports_request_id', table_name='fundamental_reports')
    op.drop_table('fundamental_reports')
    op.drop_table('flow_report_verifications')
    op.drop_table('flow_report_interpretations')
    op.drop_index('ix_agent_reports_trace_id', table_name='agent_reports')
    op.drop_index('ix_agent_reports_stock_code_created_at', table_name='agent_reports')
    op.drop_index('ix_agent_reports_client_session_id_created_at', table_name='agent_reports')
    op.drop_index('ix_agent_reports_agent_type_created_at', table_name='agent_reports')
    op.drop_table('agent_reports')
    op.drop_index('ix_technical_reports_trace_id', table_name='technical_reports')
    op.drop_index('ix_technical_reports_ticker_as_of', table_name='technical_reports')
    op.drop_index('ix_technical_reports_client_session_id_created_at', table_name='technical_reports')
    op.drop_table('technical_reports')
    op.drop_table('stocks')
    op.drop_index('ix_news_reports_created_at', table_name='news_reports')
    op.drop_table('news_reports')
    op.drop_index('ix_news_published_at', table_name='news')
    op.drop_index('ix_news_event_id', table_name='news')
    op.drop_table('news')
    op.drop_table('industry_reports')
    op.drop_index('ix_flow_reports_trace_id', table_name='flow_reports')
    op.drop_index('ix_flow_reports_ticker_base_date', table_name='flow_reports')
    op.drop_table('flow_reports')
    # ### end Alembic commands ###
    # 확장 제거(테이블 전부 제거 후). 다른 스키마가 공유할 수 있어 IF EXISTS 로만.
    # 주의: pgcrypto/vector 확장은 이 initial migration 에서만 생성/삭제한다.
    #       후속 migration 에서는 extension 을 drop 하지 않는다.
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
